matrix:
  include:
  # # Android job
  # - language: android
  #   sudo: required
  #   jdk: oraclejdk8
  #   android:
  #     env:
  #       global:
  #         - ANDROID_API_LEVEL=28
  #         - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  #         - ANDROID_ABI=armeabi-v7a
        
  #     components:
  #       - tools
  #       - platform-tools
  #       - extra-android-m2repository

  #     licenses:
  #       - 'android-sdk-preview-license-52d11cd2'
  #       - 'android-sdk-license-.+'
  #       - 'google-gdk-license-.+'
      
  #     before_install:
  #       - touch $HOME/.android/repositories.cfg
  #       - yes | sdkmanager "platforms;android-28"
  #       - yes | sdkmanager "build-tools;28.0.3"
  #       - cd Android/GitViewer
  #       - gem update --system
  #       - gem install fastlane --quiet
  #       - gem install travis-conditions
  #       - bundle install
  #       - bundle update

  #     before_cache:
  #       - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  #       - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

  #     cache:
  #         directories:
  #           - $HOME/.gradle/caches/
  #           - $HOME/.gradle/wrapper/
  #           - $HOME/.android/build-cache
      
  #     before_script:
  #         - cd $TRAVIS_BUILD_DIR/Android/GitViewer
  #         - chmod +x gradlew

  #     script:
  #         - ./gradlew dokka

  #     deploy:
  #         # Deploy a Staging version when Fabric/Staging tag is pushed
  #         - provider: script
  #           script: bundle exec fastlane deploy_staging
  #           on:
  #             branches:
  #               only:
  #                 - travisci
  #               tags: true
  #               conditions: "$TRAVIS_TAG =~ (?:Android\/Fabric\/Staging)"

  #         # Deploy a Production version when Fabric/Production tag is pushed
  #         - provider: script
  #           script: bundle exec fastlane deploy_production
  #           on:
  #             branches:
  #               only:
  #                 - travisci
  #               tags: true
  #               conditions: "$TRAVIS_TAG =~ (?:Android\/Fabric\/Production)"
                
  #         # Deploy a Production version to the Google Play Store
  #         - provider: script
  #           script: bundle exec fastlane deploy_play_store
  #           on:
  #             branches:
  #               only:
  #                 - travisci
  #             tags: true
  #             conditions: $TRAVIS_TAG =~ (?:Android\/GooglePlayStore)
      
        

  # # iOS Job
  # - language: swift
  #   sudo: required
  #   osx_image: xcode10.3
  #   ios:
  #     before_install:
  #       - echo -e "machine github.com\n  login $CI_GITHUB_TOKEN" >> ~/.netrc
  #       - cd iOS/GitViewer
  #       - gem update --system
  #       - gem install fastlane --quiet
  #       - gem install travis-conditions
  #       - gem install jazzy
  #       - bundle install
  #       - bundle update
      
  #     before_script:
  #       - cd $TRAVIS_BUILD_DIR/iOS/GitViewer
      
  #     script:
  #       - jazzy
      
  #     deploy:
  #       # Deploy a Staging version when Fabric/Staging tag is pushed
  #       - provider: script
  #         script: bundle exec fastlane deploy_staging
  #         on:
  #           branches:
  #             only:
  #               - travisci
  #             tags: true
  #             conditions: "$TRAVIS_TAG =~ (?:iOS\/Fabric\/Staging)"
        
  #       # Deploy a Production version when Fabric/Production tag is pushed
  #       - provider: script
  #         script: bundle exec fastlane deploy_production
  #         on:
  #           branches:
  #             only:
  #                 - travisci
  #             tags: true
  #             conditions: "$TRAVIS_TAG =~ (?:iOS\/Fabric\/Production)"
        
  #       # Deploy a Production version to the Apple App Store
  #       - provider: script
  #           script: bundle exec fastlane deploy_app_store
  #           on:
  #             branches:
  #               only:
  #                 - travisci
  #             tags: true
  #             conditions: $TRAVIS_TAG =~ (?:iOS\/Appstore)
  
  # Rails job
  - language: ruby
    install: true
    sudo: required
    rvm:
      - 2.5.5

    services:
      - docker

    env:
      COMPOSE_VERSION: 1.20.1

    before_install:
      - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin
      - cd  rails

    script:
      - docker-compose run web rake db:create
      - docker-compose up --build web
    
    