sudo: required
language: android
services:
  - docker
before_install:
  - docker pull user/build:latest
  - docker run -it -d --name build user/build bash
  - docker exec build git clone https://github.com/mreichelt/docker-android.git
script:
  - docker run --rm -it mreichelt/android:latest