language: android
sudo: required
jdk: oraclejdk8

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
  - cd Android/GitViewer
  - gem update --system
  - gem install fastlane --quiet
  - gem install travis-conditions
  - bundle install
  - bundle update

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_script:
  - cd $TRAVIS_BUILD_DIR/Android/GitViewer
  - chmod +x gradlew

script:
  -./gradlew dokka

deploy:
  # Deploy a Staging version when Fabric/Staging tag is pushed
  - provider: script
    script: bundle exec fastlane deploy_staging
    on:
      branches:
        only:
          - travisci
      tags: true
      conditions: "$TRAVIS_TAG =~ (?:Fabric\/Staging)"

  # Deploy a Production version when Fabric/Production tag is pushed
  - provider: script
    script: bundle exec fastlane deploy_production
    on:
      branches:
        only:
          - travisci
      tags: true
      conditions: "$TRAVIS_TAG =~ (?:Fabric\/Production)"

  # Deploy a Production version to the Google Play Store
  - provider: script
    script: bundle exec fastlane deploy_play_store
    on: 
      branches:
        only:
          - travisci
      tags: true
      conditions: $TRAVIS_TAG =~ (?:GooglePlayStore)


# jobs:
#   include:
#     - stage: deploy_staging
#       script: bundle exec fastlane deploy_staging
#     - stage: deploy_production
#       script: bundle exec fastlane deploy_production
#     - stage: deploy_playstore
#       script: bundle exec fastlane deploy_play_store
    
# stages:
#   - name: deploy_staging
#     deploy:
#       on:
#         tags: true
#         condition: "$TRAVIS_TAG =~ (?:Fabric\/Staging)"
#   - name: deploy_production
#     deploy:
#       on:
#         tags: true
#         condition: "$TRAVIS_TAG =~ (?:Fabric\/Production)"
#   - name: deploy_playstore
#     deploy:
#       on:
#         tags: true
#         condition: "$TRAVIS_TAG =~ (?:Fabric\/Production)"
