sudo: required
language: cpp
services:
  - docker
before_install:
  - docker pull mreichelt/android
  - docker run --rm -it mreichelt/android:latest
  - docker exec build git clone https://github.com/mreichelt/docker-android.git
  