version: 0.2

env:
  variables:
    ANDROID_COMPILE_SDK: "28"
    ANDROID_BUILD_TOOLS: "28.0.3"
    ANDROID_SDK_TOOLS: "4333796"

phases:
  pre_build:
    commands:
      - cd Android/GitViewer
      - gem update --system
      - gem install bundler --force
      - bundle install --path vendor/bundle
      - chmod +x ./gradlew
  build:
    commands:
      - echo "./gradlew lint"
      - echo "./gradlew dokka"
      - bundle exec fastlane deploy_staging

cache:
  paths:
    - 'vendor/bundle'
    - '/root/.gradle/caches'