version: 0.2

env:
  variables:
    ANDROID_COMPILE_SDK: "28"
    ANDROID_BUILD_TOOLS: "28.0.3"
    ANDROID_SDK_TOOLS: "4333796"

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew lint
