version: 2.1

executors:
  ios:
    macos:
      xcode: "10.2.1"
    working_directory: ~/guild-ci-test-projects/iOS/GitViewer/
  android:
    docker:
      - image: iisue/alpine-android-fastlane
    environment:
      ANDROID_COMPILE_SDK: "28"
      ANDROID_BUILD_TOOLS: "28.0.3"
      ANDROID_SDK_TOOLS: "4333796"
    working_directory: ~/guild-ci-test-projects/Android/GitViewer/

commands:
  setup_gems_ios:
    steps:
      - run: bundle install --path vendor/bundle
  setup_gems_android:
    steps:
      - run: gem update --system
      - run: gem install bundler --force
      - run: bundle install --path vendor/bundle


jobs:
  checkout_code:
    parameters:
      platform:
        description: "ios or android"
        type: enum
        enum: ["ios", "android"]
    executor: << parameters.platform >>
    working_directory: ~/guild-ci-test-projects
    steps:
      - checkout
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-<< parameters.platform >>-{{ .Environment.CIRCLE_SHA1 }}'
          paths:
            - ~/guild-ci-test-projects

  # iOS

  bundle_ios_dependencies:
    executor: ios
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-ios-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-bundle-ios-{{ checksum "Gemfile.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-bundle-ios'
      - setup_gems_ios
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-ios-{{ checksum "Gemfile.lock" }}'
          paths:
            - vendor/bundle

  fastlane_ios:
    parameters:
      command:
        description: "Fastlane command to run"
        type: string
    executor: ios
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-ios-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-ios-{{ checksum "Gemfile.lock" }}'
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-pods-ios-{{ checksum "Podfile.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-pods-ios'
      - setup_gems_ios
      - run:
          command: bundle exec fastlane << parameters.command >>
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-pods-ios-{{ checksum "Podfile.lock" }}'
          paths:
            - Pods
            - ~/.cocoapods

  # Android

  bundle_android_dependencies:
    executor: android
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-android-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-bundle-android-{{ checksum "Gemfile.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-bundle-android'
      - setup_gems_android
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-android-{{ checksum "Gemfile.lock" }}'
          paths:
            - vendor/bundle

  fastlane_android:
    parameters:
      command:
        description: "Fastlane command to run"
        type: string
    executor: android
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-android-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-android-{{ checksum "Gemfile.lock" }}'
      - setup_gems_android
      - run:
          command: bundle exec fastlane << parameters.command >>

workflows:
  build:
    jobs:
      # iOS
      - checkout_code:
          name: checkout_code_ios
          platform: ios
          context: guild-ci-test-projects-fastlane
          filters:
            tags:
              only: /.*/
      - bundle_ios_dependencies:
          context: guild-ci-test-projects-fastlane
          requires:
            - checkout_code_ios
          filters:
            tags:
              only: /.*/
      - fastlane_ios:
          name: lint_ios
          command: lint
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_ios_dependencies
          filters:
            tags:
              only: /.*/
      - fastlane_ios:
          name: build_and_deploy_ios_staging
          command: deploy_staging
          context: guild-ci-test-projects-fastlane
          requires:
            - lint_ios
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^Fabric/Staging/.*$/
      - fastlane_ios:
          name: build_and_deploy_ios_production
          command: deploy_production
          context: guild-ci-test-projects-fastlane
          requires:
            - lint_ios
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^Fabric/Production/.*$/
      - fastlane_ios:
          name: build_and_deploy_ios_release
          command: deploy_app_store
          context: guild-ci-test-projects-fastlane
          requires:
            - lint_ios
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^Appstore/.*$/
      # Android
      - checkout_code:
          name: checkout_code_android
          platform: android
          context: guild-ci-test-projects-fastlane
          filters:
            tags:
              only: /.*/
      - bundle_android_dependencies:
          context: guild-ci-test-projects-fastlane
          requires:
            - checkout_code_android
          filters:
            tags:
              only: /.*/
      - fastlane_android:
          name: build_and_deploy_android_staging
          command: deploy_staging
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_android_dependencies
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^Fabric/Staging/.*$/
      - fastlane_android:
          name: build_and_deploy_android_production
          command: deploy_production
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_android_dependencies
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^Fabric/Production/.*$/
      - fastlane_android:
          name: build_and_deploy_android_release
          command: deploy_play_store
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_android_dependencies
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^GooglePlayStore/.*$/
