version: 2.1

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.6.3-node
    working_directory: ~/guild-ci-test-projects
    steps:
      - checkout
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-{{ .Environment.CIRCLE_SHA1 }}'
          paths:
            - ~/guild-ci-test-projects

  bundle_dependencies:
    parameters:
      platform:
        description: "iOS or Android"
        type: enum
        enum: ["iOS", "Android"]
    docker:
      - image: circleci/ruby:2.6.3-node
    working_directory: ~/guild-ci-test-projects/<< parameters.platform >>/GitViewer/
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-bundle-<< parameters.platform >>-{{ checksum "Gemfile.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-bundle-<< parameters.platform >>'
      - run: gem update --system
      - run: gem install bundle
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-<< parameters.platform >>-{{ checksum "Gemfile.lock" }}'
          paths:
            - vendor/bundle

  bundle_pods:
    docker:
      - image: circleci/ruby:2.6.3-node
    working_directory: ~/guild-ci-test-projects/<< parameters.platform >>/GitViewer/
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-iOS-{{ checksum "Gemfile.lock" }}'
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-pods-iOS-{{ checksum "Podfile.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-pods-iOS'
      - run: gem update --system
      - run: gem install bundle
      - run: bundle install --path vendor/bundle
      - run: bundle exec pod install
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-pods-iOS-{{ checksum "Podfile.lock" }}'
          paths:
            - Pods

  fastlane:
    parameters:
      platform:
        description: "iOS or Android"
        type: enum
        enum: ["iOS", "Android"]
      command:
        description: "Fastlane command to run"
        type: string
    docker:
      - image: circleci/ruby:2.6.3-node
    working_directory: ~/guild-ci-test-projects/<< parameters.platform >>/GitViewer/
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-<< parameters.platform >>-{{ checksum "Gemfile.lock" }}'
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-pods-<< parameters.platform >>-{{ checksum "Podfile.lock" }}'
      - run: gem update --system
      - run: gem install bundle
      - run: bundle install --path vendor/bundle
      - run:
          command: bundle exec fastlane << parameters.command >>

workflows:
  build:
    jobs:
      - checkout_code:
          context: guild-ci-test-projects-fastlane
      - bundle_dependencies:
          name: bundle_ios_dependencies
          platform: iOS
          context: guild-ci-test-projects-fastlane
          requires:
            - checkout_code
      - bundle_pods:
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_ios_dependencies
      - fastlane:
          name: lint-ios
          platform: iOS
          command: lint
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_pods
      - fastlane:
          name: build-and-deploy-ios-staging
          platform: iOS
          command: deploy_staging
          context: guild-ci-test-projects-fastlane
          requires:
            - lint-ios
          filters:
            branches:
              only: /Fabric/Staging/.*$/
      - fastlane:
          name: build-and-deploy-ios-production
          platform: iOS
          command: deploy_production
          context: guild-ci-test-projects-fastlane
          requires:
            - lint-ios
          filters:
            branches:
              only: /Fabric/Production/.*$/
      - fastlane:
          name: build-and-deploy-ios-release
          platform: iOS
          command: deploy_app_store
          context: guild-ci-test-projects-fastlane
          requires:
            - lint-ios
          filters:
            branches:
              only: /Appstore/.*$/
