version: 2.1

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.6.3-node
    working_directory: ~/guild-ci-test-projects
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/guild-ci-test-projects

  bundle_dependencies:
    parameters:
      platform:
        description: "iOS or Android"
        type: enum
        enum: ["iOS", "Android"]
    docker:
      - image: circleci/ruby:2.6.3-node
    working_directory: ~/guild-ci-test-projects/<< parameters.platform >>/GitViewer
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-<< parameters.platform >>-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-<< parameters.platform >>-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/guild-ci-test-projects/<< parameters.platform >>/vendor/bundle

  fastlane:
    parameters:
      platform:
        description: "iOS or Android"
        type: enum
        enum: ["iOS", "Android"]
      command:
        description: "Fastlane command to run"
        type: string
    docker:
      - image: circleci/ruby:2.6.3-node
    working_directory: ~/guild-ci-test-projects/<< parameters.platform >>/GitViewer
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-<< parameters.platform >>-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle exec fastlane << parameters.command >>

workflows:
  build:
    jobs:
      - checkout_code
      - bundle_dependencies:
          name: bundle_ios_dependencies
          platform: iOS
          requires:
            - checkout_code
      - fastlane:
          name: lint-ios
          platform: iOS
          command: lint
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_ios_dependencies
      - fastlane:
          name: build-and-deploy-ios-staging
          platform: iOS
          command: deploy_staging
          context: guild-ci-test-projects-fastlane
          requires:
            - lint-ios
          filters:
            branches:
              only: /Fabric/Staging/.*$/
      - fastlane:
          name: build-and-deploy-ios-production
          platform: iOS
          command: deploy_production
          context: guild-ci-test-projects-fastlane
          requires:
            - lint-ios
          filters:
            branches:
              only: /Fabric/Production/.*$/
      - fastlane:
          name: build-and-deploy-ios-release
          platform: iOS
          command: deploy_app_store
          context: guild-ci-test-projects-fastlane
          requires:
            - lint-ios
          filters:
            branches:
              only: /Appstore/.*$/
