version: 2.1

executors:
  ios:
    docker:
      - image: circleci/ruby:2.6.3-node
    working_directory: ~/guild-ci-test-projects/iOS/GitViewer/
  android:
    docker:
      - image: iisue/alpine-android-fastlane
    environment:
      ANDROID_COMPILE_SDK: "28"
      ANDROID_BUILD_TOOLS: "28.0.3"
      ANDROID_SDK_TOOLS: "4333796"
    working_directory: ~/guild-ci-test-projects/Android/GitViewer/

commands:
  setup_gems:
    steps:
      - run: gem update --system
      - run: gem install bundle
      - run: bundle install --path vendor/bundle

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.6.3-node
    working_directory: ~/guild-ci-test-projects
    steps:
      - checkout
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-{{ .Environment.CIRCLE_SHA1 }}'
          paths:
            - ~/guild-ci-test-projects

  bundle_ios_dependencies:
    executor: ios
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-bundle-iOS-{{ checksum "Gemfile.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-bundle-iOS'
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-pods-iOS-{{ checksum "Podfile.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-pods-iOS'
      - setup_gems
      - run: bundle exec pod install
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-iOS-{{ checksum "Gemfile.lock" }}'
          paths:
            - vendor/bundle
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-pods-iOS-{{ checksum "Podfile.lock" }}'
          paths:
            - Pods
            - ~/.cocoapods

  fastlane_ios:
    parameters:
      command:
        description: "Fastlane command to run"
        type: string
    executor: ios
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-iOS-{{ checksum "Gemfile.lock" }}'
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-pods-iOS-{{ checksum "Podfile.lock" }}'
      - setup_gems
      - run:
          command: bundle exec fastlane << parameters.command >>

  bundle_android_dependencies:
    executor: android
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION }}-bundle-Android-{{ checksum "Gemfile.lock" }}'
            - '{{ .Environment.CACHE_VERSION }}-bundle-Android'
      - setup_gems
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-Android-{{ checksum "Gemfile.lock" }}'
          paths:
            - vendor/bundle

  fastlane_android:
    parameters:
      command:
        description: "Fastlane command to run"
        type: string
    executor: android
    steps:
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-repo-{{ .Environment.CIRCLE_SHA1 }}'
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION }}-bundle-Android-{{ checksum "Gemfile.lock" }}'
      - setup_gems
      - run:
          command: bundle exec fastlane << parameters.command >>

workflows:
  build:
    jobs:
      - checkout_code:
          context: guild-ci-test-projects-fastlane
      # iOS
      - bundle_ios_dependencies:
          platform: iOS
          context: guild-ci-test-projects-fastlane
          requires:
            - checkout_code
      - fastlane_ios:
          name: lint_ios
          command: lint
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_ios_dependencies
      - fastlane_ios:
          name: build_and_deploy_ios_staging
          command: deploy_staging
          context: guild-ci-test-projects-fastlane
          requires:
            - lint_ios
          filters:
            tags:
              only: /^Fabric/Staging/.*$/
      - fastlane_ios:
          name: build_and_deploy_ios_production
          command: deploy_production
          context: guild-ci-test-projects-fastlane
          requires:
            - lint_ios
          filters:
            tags:
              only: /^Fabric/Production/.*$/
      - fastlane_ios:
          name: build_and_deploy_ios_release
          command: deploy_app_store
          context: guild-ci-test-projects-fastlane
          requires:
            - lint_ios
          filters:
            tags:
              only: /^Appstore/.*$/
      # Android
      - bundle_dependencies:
          name: bundle_android_dependencies
          platform: Android
          context: guild-ci-test-projects-fastlane
          requires:
            - checkout_code
      - fastlane_android:
          name: build_and_deploy_android_staging
          command: deploy_staging
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_android_dependencies
          filters:
            tags:
              only: /^Fabric/Staging/.*$/
      - fastlane_android:
          name: build_and_deploy_android_production
          command: deploy_production
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_android_dependencies
          filters:
            tags:
              only: /^Fabric/Production/.*$/
      - fastlane_android:
          name: build_and_deploy_android_release
          command: deploy_play_store
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_android_dependencies
          filters:
            tags:
              only: /^GooglePlayStore/.*$/
