version: 2.1

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/guild-ci-test-projects
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/guild-ci-test-projects

  bundle_dependencies:
    parameters:
      platform:
        description: "iOS or Android"
        type: enum
        enum: ["iOS", "Android"]
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/guild-ci-test-projects/<< parameters.platform >>
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-<< parameters.platform >>-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-<< parameters.platform >>-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/guild-ci-test-projects/<< parameters.platform >>/vendor/bundle

  fastlane:
    parameters:
      platform:
        description: "iOS or Android"
        type: enum
        enum: ["iOS", "Android"]
      command:
        description: "Fastlane command to run"
        type: string
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/guild-ci-test-projects/<< parameters.platform >>
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-<< parameters.platform >>-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle exec fastlane << parameters.command >>

  rails_test:
    docker:
      - image: circleci/ruby:2.5.5-node
        environment:
          SELENIUM_DRIVER_URL: http://localhost:4444/wd/hub
          DATABASE_HOST: localhost
          RAILS_ENV: test
          BUNDLE_PATH: ~/bundle
      - image: circleci/postgres
      - image: selenium/standalone-chrome:3.5.3
    working_directory: ~/guild-ci-test-projects/rails
    steps:
      - checkout:
          path: ~/guild-ci-test-projects
      - restore_cache:
          key: v2-rails-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install
      - save_cache:
          key: v2-rails-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - "{{ .Environment.BUNDLE_PATH }}"
      - run:
          command: bundle exec db:create
      - run:
          command: bundle exec rails db:migrate
      - run:
          command: bundle exec rspec
      - store_artifacts:
          path: ~/guild-ci-test-projects/rails/tmp/screenshots
          destination: screenshots

workflows:
  build:
    jobs:
      - checkout_code
      - bundle_dependencies:
          name: bundle_ios_dependencies
          platform: iOS
          requires:
            - checkout_code
          filters:
            branches:
              only: /iOS/.*$/
      - fastlane:
          name: lint-ios
          platform: iOS
          command: lint
          context: guild-ci-test-projects-fastlane
          requires:
            - bundle_ios_dependencies
          filters:
            branches:
              only: /iOS/.*$/
      - fastlane:
          name: build-and-deploy-ios-staging
          platform: iOS
          command: deploy_staging
          context: guild-ci-test-projects-fastlane
          requires:
            - lint-ios
          filters:
            branches:
              only: /Fabric/Staging/.*$/
      - fastlane:
          name: build-and-deploy-ios-production
          platform: iOS
          command: deploy_production
          context: guild-ci-test-projects-fastlane
          requires:
            - lint-ios
          filters:
            branches:
              only: /Fabric/Production/.*$/
      - fastlane:
          name: build-and-deploy-ios-release
          platform: iOS
          command: deploy_app_store
          context: guild-ci-test-projects-fastlane
          requires:
            - lint-ios
          filters:
            branches:
              only: /Appstore/.*$/

  rails_test:
    jobs:
      - rails_test
