name: GitViewer Android Production Deployment

on:
  push:
    branches:
      - Github_Actions
    tags:
      - 'Fabric/Production/*'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
  
    # Before starting setup everything needed here!
    - name: Pre-Setup
      working-directory: ./Android/GitViewer
      run: |
        bundle install
        
    # Deploy Staging version to Fabric
    - name: Run Fastlane Deploy Production
      env: 
        KEYSTORE_PASS:        ${{ secrets.KEYSTORE_PASS }}
        KEYSTORE_ALIAS:       ${{ secrets.KEYSTORE_ALIAS }}
        FABRIC_BUILD_SECRET:  ${{ secrets.FABRIC_BUILD_SECRET }}
        FABRIC_TOKEN:         ${{ secrets.FABRIC_TOKEN }}
        RELEASE_SLACK_URL:    ${{ secrets.RELEASE_SLACK_URL }}
      working-directory: ./Android/GitViewer
      run: |
        bundle exec fastlane deploy_production --verbose

    # Generate documentation
    - name: Generate documentation
      working-directory: ./Android/GitViewer
      run: |
        ./gradlew dokka