name: GitViewer Deployment

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    # Before starting Fastlane setup everything needed here!
    -name: Pre-Setup
      working-directory: ./iOS/GitViewer
      run: |
        bundle install
        gem install CFPropertyList

    # Setup Fastlane for Github Actions use
    - name: Run Fastlane setup
      env:
        APPLE_ACCOUNT:  ${{ secrets.APPLE_ACCOUNT }}
        TEAM_ID:        ${{ secrets.TEAM_ID }}
      working-directory: ./iOS/GitViewer
      run: |
        bundle exec fastlane setup --verbose

    # Deploy a staging version to Fabric
    - name: Run Fastlane Deploy Staging
      env:
        MATCH_REPO:           ${{ secrets.MATCH_REPO }}
        MATCH_PASSWORD:       ${{ secrets.MATCH_PASS }}
        SIGNING_ID:           ${{ secrets.APPLE_ACCOUNT }}
        TEAM_ID:              ${{ secrets.TEAM_ID }}
        FABRIC_BUILD_SECRET:  ${{ secrets.FABRIC_BUILD_SECRET }}
        FABRIC_TOKEN:         ${{ secrets.FABRIC_TOKEN }}
        RELEASE_SLACK_URL:    ${{ secrets.RELEASE_SLACK_URL }}
      working-directory: ./iOS/GitViewer
      run: |
        bundle exec fastlane deploy_staging --verbose
        
